// Generated by LiveScript 1.3.1
(function(){
  var fs, express, app, x$;
  fs = require('fs');
  express = require('express');
  app = express();
  x$ = app;
  x$.use(express.compress({
    filter: function(req, res){
      return /json|text|javascript|css/.test(res.getHeader('Content-Type'));
    },
    level: 9
  }));
  app.get('/', function(req, res){
    return res.sendfile('bootstrap.css');
  });
  app.listen(8080);
}).call(this);
